[package]
name = "rslighty"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = true
opt-level = "z" 
lto = true

[dependencies]
clap = { version = "4.5.34", features = ["cargo", "derive"] }
