[package]
name = "rslighty"
version = "0.2.0"
edition = "2024"

[profile.release]
strip = true
opt-level = "z" 
lto = true

[dependencies]
clap = { version = "4.5.34", features = ["cargo", "derive"] }
thiserror = "2.0.12"
